---
title: Convenience is an Enemy
output:
    html_document:
        css: stylesheet.css
        theme: null
        highlight: null
        mathjax: null
---

<table>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<table>

Convenience can be a wonderful thing but it is just as much a bringer of destruction as it is a savior. The reason is because convenience leads to comfort and comfort leads to complacency. Some level of comfort is necessary for a quality life, but I will make the argument that some level of <i>dis</i>comfort is also necessary.

First I want to examine why complacency is bad. Complacency makes a person unwilling to make changes to themselves or the world around them, and they become complacent because of conveniences that they're used to. Making changes is inconvenient and change can potentially undo the convenience that they worked for. The phrase "if it ain't broke, don't fix it" is common for that reason. My job has a computer used for installing firmware on clock chips for certain devices. The computer is at least twenty years old, runs Windows 95, and could die any day for any reason and we would be absolutely stranded without it, but the inconvenience of upgrading it is enough of a deterrent to leave it as it is despite that. It is more convenient to keep using a decrepit machine than it is to replace it.

Complacency is not a matter of mere laziness, though it is easy to conflate the two. Laziness would be avoiding changing the computer even after it breaks. Complacency leads to avoidance only where convenience is at stake. Taking the same route home from work, for example, is a matter of complacency because to take an unfamiliar route is less convenient than one you already know. Complacent people seek to minimize threats to convenience, whereas lazy people seek to do as little as possible regardless.

So how does one avoid complacency? Since complacency is minimizing threats to convenience, then it follows that to avoid complacency you must impose inconvenience and discomfort upon yourself voluntarily. That can involve seeking out challenges, reducing your possessions, or upgrading a deprecated computer. Basically it involves being active in some area where you would rather not be because you've already found the path of least resistance. But resistance is valuable because it instills discipline, and discipline wards off complacency.

And second I want to examine why some discomfort is good. Discomfort is what causes and allows people to be vigilant and stalwart. With a life full of comfort there is no reason to do anything that invokes any change. There is no reason to seek to do good in the world because for you all is already good. Discomfort creates empathy among others. The Buddha understood that a life full of comfort creates awful people, which is why he left his royalty behind in favor of a humble life. It's not necessary to be so extreme, but I believe it is definitely necessary to purposefully induce discomfort in your own life.

Go out and do things which are inconvenient or uncomfortable. Your life will be better.

### [**🏠**](index.html)<br><br>
