---
title: Freedom and the Consolidation of Power
output:
    html_document:
        css: stylesheet.css
        theme: null
        highlight: null
        mathjax: null
---

<table>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<table>

The number one threat to Freedom is the consolidation of power in any form. It gives someone control, in one way or another, over someone else. When power is decentralized there is no control; when there is no control there is no power; when there is no power there is Freedom.

One of the best examples of consolidation of power is in software. Microsoft, Apple, Google, and Amazon (and a small number of other companies) control over 90% of the software in the United States, if not the world. Thus, they control over 90% of the people who use their software. On one hand their domination of software gives us software standards, but on the other hand it also means we have no freedom when it comes to our computers and phones. You cannot modify the software in a Windows or Mac OS computer in ways which Microsoft and Apple don't agree with, even if doing so would be beneficial to you, because to do so would be to *break the licence agreement* that, despite having not read, you agreed to.

You also cannot share the software on your Windows or Apple computer (unless it is [Free Software](http://fsf.org)). People who do share software are labeled **pirates**, despite the fact that they haven't actually stolen anything. They simply commited the crime of sharing with their neighbor. Given these facts, one has to conclude that the software on your computer *doesn't belong to you*. In fact, the EULA (End User License Agreement) that you agree to before using your computer often states that it belongs to Microsoft or Apple, and you are simply paying for the privilege of using it. In that manner, these companies are in full control because power has consolidated to them. In a world where power lies in the users, it is decentralized, and thus users are Free.

Another example of consolidation of power is in agriculture. A hundred years ago agriculture was mostly small farms, but now a few companies control the agriculture of entire nations. That means that they have control over the food you eat, and thus they have control over you. That isn't to say that they abuse this control (as this leads to other arguments), but the fact that they have it should be worrying. In a world where everyone is capable of producing their own sustenance, however, there is no consolidation of power in agriculture because everyone is free to provide the food that they want.

Now, it is perfeclty reasonable to come to another conclusion, that consolidation of power in agriculture is actually good. For one thing, a centralized agriculture industry increases efficiency--in the sense that crops are able to be moved from one area to another with ease. In addition, it allows people to do work that isn't agriculture. But these arguments are based upon a false premise, which is that people cannot grow for themselves without investing all of their time into farming, but the fact of the matter is actually the [opposite](https://en.wikipedia.org/wiki/Aquaponics"). By utilizing aquaponic or hydroponic technology, anybody can grow their own produce. If people were willing to give up eating beef and pork in the amount that we currently do (i.e., way too much), then everybody could be self-sustaining. And even given that not everyone would be willing to grow for themselves, having numerous local farms would still be viable, feasible, and entirely possible.

There is consolidation of power in *basically every industry*, and I believe that we could achieve all of the same successes with more freedom for the people. The fact is that consolidation of power stifles competition, creates huge barriers, and limits consumers. It gives us the illusion of free choice by convincing us that we cannot fend for ourselves. My hope is that in the near future, not only will people realize that they can be self-determined, but that people will grow to understand the implications of giving responsibility to another for things which can be done yourself.

### [**🏠**](index.html)<br><br>
